import streamlit as st

st.set_page_config(page_title='QuLab', layout='wide')
st.sidebar.image('https://www.quantuniversity.com/assets/img/logo5.jpg')
st.sidebar.divider()
st.title('QuLab')
st.divider()
st.markdown("""
In this lab, explore AI security vulnerabilities through interactive simulations and visualizations.
""")

page = st.sidebar.selectbox('Navigation', ['Overview', 'Simulation'])
if page == 'Overview':
    from application_pages.page_1 import main
    main()
elif page == 'Simulation':
    from application_pages.page_2 import main
    main()


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
''')
