import streamlit as st

st.set_page_config(page_title="AI Security Vulnerability Simulation Lab", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("AI Security Vulnerability Simulation Lab")
st.divider()

page = st.sidebar.selectbox(label="Navigation", options=["Introduction", "Setup", "Configuration", "Simulation", "Visualization"])

if page == "Introduction":
    from application_pages.introduction import main
    main()
elif page == "Setup":
    from application_pages.setup import main
    main()
elif page == "Configuration":
    from application_pages.configuration import main
    main()
elif page == "Simulation":
    from application_pages.simulation import main
    main()
elif page == "Visualization":
    from application_pages.visualization import main
    main()


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
''')
